# Walkthrough

The aim of this notebook is to do a complete tour of the functionalities and possibilities of `Analytical-Satsky`.

## 1. Imports
We start by importing standard libraries and the needed functions.

In [4]:
import numpy as np
import pandas as pd
import astropy.units as u
from astropy.coordinates import EarthLocation

from analytical_satsky import compute_occupancy_fraction
from analytical_satsky import load_constellation, list_constellations
from analytical_satsky import MultiShellObs


%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

### 2. Shells

Many orbital shells are predefined within `Analytical-Satsky`. They are regrouped in one DataFrame for each major constellation.

To know the available constellations use `list_constellations`

In [7]:
print(list_constellations())

['guowang', 'leo', 'oneweb', 'qianfan', 'starlink_filing1', 'starlink_filing2', 'starlink_march25', 'starlink_scaled40000']

You can then use `load_constellation`, that can take as argument several strings. They must be part of the list above, but it is case insensitive.

In [11]:
guowang_and_leo = load_constellation("guowang", "leo")
guowang_and_leo

      i     h     n
0  85.0   590   480
1  50.0   600  2000
2  55.0   508  3600
3  30.0  1145  1728
4  40.0  1145  1728
5  50.0  1145  1728
6  60.0  1145  1728
7  51.9   630  1156
8  42.0   610  1296
9  33.0   590   784

You can also create your own constellation configuration, as long as you respect the Dataframe organization

In [14]:
my_const = pd.DataFrame(columns=['i', 'h', 'n'], data=[[45, 500, 1000], [45, 1000, 200]])
my_const

    i     h     n
0  45   500  1000
1  45  1000   200